# Generated by Django 4.0.4 on 2022-05-18 11:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name_plural': 'libraries'},
        ),
        migrations.CreateModel(
            name='ReadingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('seats_count', models.PositiveIntegerField()),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraries.library')),
            ],
            options={
                'unique_together': {('library', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('reading_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraries.readingroom')),
            ],
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_no', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('shelf_no', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('reading_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraries.readingroom')),
            ],
            options={
                'unique_together': {('reading_room', 'rack_no', 'shelf_no')},
            },
        ),
    ]
