# Generated by Django 4.0.4 on 2022-05-18 23:13

from django.db import migrations, models
import django.db.models.deletion
import libraries.validators


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
        ('libraries', '0002_alter_library_options_readingroom_librarian_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagelocation',
            name='publications',
            field=models.ManyToManyField(to='publications.publication'),
        ),
        migrations.CreateModel(
            name='PublicationsFlowHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(validators=[libraries.validators.validate_not_zero])),
                ('librarian', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='libraries.librarian')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='publications.publication')),
            ],
        ),
    ]
