# Generated by Django 4.0.4 on 2022-05-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
        ('libraries', '0003_storagelocation_publications_publicationsflowhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagelocation',
            name='publications',
            field=models.ManyToManyField(blank=True, to='publications.publication'),
        ),
    ]
