# Generated by Django 4.0.4 on 2022-05-25 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0004_alter_storagelocation_publications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicationsflowhistory',
            options={'verbose_name_plural': 'publications flow history'},
        ),
    ]
