# Generated by Django 4.0.4 on 2022-06-01 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0005_alter_publicationsflowhistory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationsflowhistory',
            name='record_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
