# Generated by Django 4.0.4 on 2022-05-18 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libraries', '0003_storagelocation_publications_publicationsflowhistory'),
        ('readers', '0001_initial'),
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LendingRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('library_rooms_only', models.BooleanField()),
                ('time_limit', models.DurationField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('library_rooms_only', 'time_limit')},
            },
        ),
        migrations.CreateModel(
            name='PublicationsOrdersHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_timestamp', models.DateTimeField(auto_now_add=True)),
                ('received_timestamp', models.DateTimeField(blank=True, null=True)),
                ('given_librarian', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='given_publications_orders', to='libraries.librarian')),
                ('lending_restriction', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lending.lendingrestriction')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='publications.publication')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='readers.reader')),
                ('received_librarian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='received_publications_orders', to='libraries.librarian')),
            ],
        ),
    ]
