# Generated by Django 4.0.4 on 2022-05-18 23:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import libraries.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiteracyWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('pages', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('publication_date', models.DateField()),
                ('count', models.PositiveIntegerField()),
                ('literacy_works', models.ManyToManyField(to='publications.literacywork')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleLiteracyWork',
            fields=[
                ('literacywork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publications.literacywork')),
                ('theme', models.CharField(max_length=255)),
            ],
            bases=('publications.literacywork',),
        ),
        migrations.CreateModel(
            name='BookPublication',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publications.publication')),
                ('category', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=255, unique=True)),
            ],
            bases=('publications.publication',),
        ),
        migrations.CreateModel(
            name='JournalPublication',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publications.publication')),
                ('discipline', models.CharField(max_length=255)),
                ('editor', models.CharField(max_length=255)),
                ('frequency', models.DurationField()),
            ],
            bases=('publications.publication',),
        ),
        migrations.CreateModel(
            name='NovelLiteracyWork',
            fields=[
                ('literacywork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publications.literacywork')),
                ('genre', models.CharField(max_length=255)),
            ],
            bases=('publications.literacywork',),
        ),
        migrations.CreateModel(
            name='PaperPublication',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publications.publication')),
                ('category', models.CharField(max_length=255)),
                ('editor', models.CharField(max_length=255)),
                ('frequency', models.DurationField()),
            ],
            bases=('publications.publication',),
        ),
        migrations.CreateModel(
            name='PoemLiteracyWork',
            fields=[
                ('literacywork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publications.literacywork')),
                ('theme', models.CharField(max_length=255)),
            ],
            bases=('publications.literacywork',),
        ),
        migrations.CreateModel(
            name='ScientificLiteracyWork',
            fields=[
                ('literacywork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publications.literacywork')),
                ('subject', models.CharField(max_length=255)),
            ],
            bases=('publications.literacywork',),
        ),
        migrations.CreateModel(
            name='TextbookLiteracyWork',
            fields=[
                ('literacywork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publications.literacywork')),
                ('subject', models.CharField(max_length=255)),
            ],
            bases=('publications.literacywork',),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.DateField(validators=[libraries.validators.validate_date_in_past])),
                ('death_date', models.DateField(blank=True, null=True, validators=[libraries.validators.validate_date_in_past])),
                ('literacy_works', models.ManyToManyField(to='publications.literacywork')),
            ],
        ),
    ]
