# Generated by Django 4.0.4 on 2022-05-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='literacy_works',
        ),
        migrations.AddField(
            model_name='literacywork',
            name='literacy_works',
            field=models.ManyToManyField(to='publications.author'),
        ),
    ]
