# Generated by Django 4.0.4 on 2022-05-25 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_remove_author_literacy_works_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='literacywork',
            old_name='literacy_works',
            new_name='authors',
        ),
    ]
