# Generated by Django 4.0.4 on 2022-05-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_rename_literacy_works_literacywork_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literacywork',
            name='authors',
            field=models.ManyToManyField(related_name='literacy_works', to='publications.author'),
        ),
    ]
