# Generated by Django 4.0.4 on 2022-05-18 23:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libraries', '0003_storagelocation_publications_publicationsflowhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='libraries.librarian')),
                ('issuer_library', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='libraries.library')),
            ],
        ),
        migrations.CreateModel(
            name='RetireeReader',
            fields=[
                ('reader_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='readers.reader')),
                ('years_work_experience', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            bases=('readers.reader',),
        ),
        migrations.CreateModel(
            name='StudentReader',
            fields=[
                ('reader_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='readers.reader')),
                ('educational_institution', models.CharField(max_length=255)),
                ('group_no', models.PositiveIntegerField()),
            ],
            bases=('readers.reader',),
        ),
        migrations.CreateModel(
            name='TeacherReader',
            fields=[
                ('reader_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='readers.reader')),
                ('educational_institution', models.CharField(max_length=255)),
            ],
            bases=('readers.reader',),
        ),
        migrations.CreateModel(
            name='WorkerReader',
            fields=[
                ('reader_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='readers.reader')),
                ('organization', models.CharField(max_length=255)),
            ],
            bases=('readers.reader',),
        ),
    ]
